Updates

diff --git a/wenv/wenvs/inspire-vagrant b/wenv/wenvs/inspire-vagrant
--- a/wenv/wenvs/inspire-vagrant
+++ b/wenv/wenvs/inspire-vagrant
@@ -19,6 +19,33 @@ wenv_def() {
     bootstrap_wenv() {}
 }
 
+# curl with auth included
+# curl various endpoints
+curli() {
+    local url
+    case "$1" in
+        v|vagrant)
+            url='http://inspirefitness.vm:9090'
+            ;;
+        b|beta)
+            url='https://beta.inspirefitness.com/api/studio-manager'
+            ;;
+        *)
+            echo "error: unsupported destination '$1'" >&2
+            return 1
+            ;;
+    esac
+    shift
+
+    local request=$(printf '%s' "$1" | tr '[a-z]' '[A-Z]')
+    shift
+
+    local dst="$1"
+    shift
+
+    curla -X"$request" "$url$dst" $@
+}
+
 export GITLAB_PRIVATE_KEY="$HOME/.ssh/git"
 export HOST_PRIVATE_KEY="$HOME/.ssh/vm-inspire"
 
@@ -53,7 +80,7 @@ vagrant_run_go() {
             cmd="cd dev/$1; go fmt ./...; go build"
             ;;
         'run')
-            cmd="cd dev/$1; go fmt ./...; go build && ./$1"
+            cmd="cd dev/$1; go fmt ./...; go build && ./$@"
             ;;
     esac
     vagrant_run_persist "$cmd"
@@ -87,8 +114,8 @@ broadcast() {
 }
 
 vagrant_run_sql() {
-        scp db.sql inspire-vagrant:~
-        vagrant_run 'sudo cp db.sql ~postgres/dgrisham-tmp-db.sql && sudo su -l postgres -c "psql -f ~/dgrisham-tmp-db.sql"'
+    scp db.sql inspire-vagrant:~
+    vagrant_run 'sudo cp db.sql ~postgres/dgrisham-tmp-db.sql && sudo su -l postgres -c "psql -f ~/dgrisham-tmp-db.sql"'
 }
 alias vsql='vagrant_run_sql'
 
