commit

diff --git a/zsh/aliases b/zsh/aliases
--- a/zsh/aliases
+++ b/zsh/aliases
@@ -4,6 +4,44 @@
 # ---------------------
 alias scurl='curl -w "%{http_code}"'
 
+# beet ipfs
+# ---------
+
+publish_library() {
+    local topic='grish-work-library'
+    local library_hash=$(beet ipfs --publish 2>&1 | ag -o '(?<=ipfs: hash of library: )Qm.*?$')
+    [[ -z "$library_hash" ]] && { echo "failed to publish beet library to ipfs" ; return 1 ; }
+    ipfs pubsub pub $topic $library_hash
+}
+
+# alias publish_library='ipfs name publish /ipfs/$(beet ipfs --publish 2>&1 | ag --nocolor -o "(?<=ipfs: hash of library: )Qm.*?$")'
+alias fetch_library='beet ipfs --import $(ipfs name resolve /ipns/QmPDZYSLVUiFWHztvFPXRmvaVZp217kL1hgZ35jEyXqNj6 | sed "s|/ipfs/||")'
+
+ipfs_connect() {
+    port="$1"
+    [[ -z "$port" ]] && { echo "port required" >&2 ; return 1 ; }
+    ipfs swarm connect "/ip4/73.3.139.32/tcp/$port/p2p/QmPDZYSLVUiFWHztvFPXRmvaVZp217kL1hgZ35jEyXqNj6"
+}
+
+subscribe_to_library() {
+    topic='grish-desktop-library'
+    [[ -n "$1" ]] && topic="$1"
+    echo "subscribing to topic '$topic'"
+
+    ipfs pubsub sub --encoding json $topic \
+    | jq --raw-output --unbuffered ".data" \
+    | while read data; do
+        libHash=$(base64 --decode <<<$data)
+        echo "importing library $libHash as $topic"
+        beet ipfs --import $libHash $topic && echo "successfully imported library $libHash"
+    done
+}
+
+ipfs_local_stat() {
+    ipfs files stat --with-local /ipfs/$1
+}
+alias ils=ipfs_local_stat
+
 # colored echo
 # ------------
 
@@ -277,7 +315,7 @@ alias ta='unbuffer task active | sed \$d'
 # ag default options
 # ==================
 
-alias ag="/bin/ag --color-path='1;36' --color-line-number='0;37' --color-match='1;33'"
+alias ag="/bin/ag --color --color-path='1;36' --color-line-number='0;37' --color-match='1;33'"
 
 # skim + ag to interactively grep files
 
